# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e38c9e6463e93e5c12ec9b3249729d15"
name = "BOGO, Bundles & Free Gifts"
handle = "bogo-discounts-2"
application_url = "https://intro-keyboards-away-remainder.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = ["https://intro-keyboards-away-remainder.trycloudflare.com/auth/callback", "https://intro-keyboards-away-remainder.trycloudflare.com/auth/shopify/callback", "https://intro-keyboards-away-remainder.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
