api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "bogo-bundles-free-gift"

uid = "0199326d-2d80-7a3d-b791-b169da013d50"

type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
